# This is a sample build configuration for all languages.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
# image: docker-image:tag

pipelines:
    default:
      - step:
          script:
            - echo "Pipeline Init"
            - apt-get update
            - apt-get -qq install git-ftp
            - echo "'_$(git status -uno --porcelain | wc -l)_'"
            - git status -uno --porcelain
            - echo "Initiating push site:/"
            - git config git-ftp.syncroot /
            - git ftp commit --user $FTP_USER --passwd $FTP_PASSWORD ftp://$FTP_SERVER/mainwave.co.uk